ci:
  autofix_prs: false
  autoupdate_schedule: monthly

# Specify the default version of Ruby in case it is not installed
default_language_version:
  ruby: 2.7.2

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-ast
    name: validate Python code
  - id: check-merge-conflict
    name: check for git merge conflicts
    exclude: .*\.rst
  - id: check-case-conflict
    name: check for filename case conflicts
  - id: name-tests-test
    args: [--pytest-test-first]
    exclude: src/plasmapy/tests/_helpers/.*
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/sirosen/texthooks
  rev: 0.6.6
  hooks:
  - id: fix-smartquotes
  - id: fix-spaces
  - id: fix-ligatures
  - id: forbid-bidi-controls

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    # For the labeler GitHub Action, labels with spaces in them must
    # be put in quotes. However, the pretty-format-yaml hook will
    # remove the quotes which will break that action, so we should not
    # run this hook on `labeler.yml` (or certain other files).
    exclude: .github/labeler.yml|.pre-commit-search-and-replace.yaml

- repo: https://github.com/mattlqx/pre-commit-search-and-replace
  rev: v1.0.5
  hooks:
  - id: search-and-replace
    exclude: changelog/README.rst|docs/changelog/.*|.sourcery.yaml|docs/_global_substitutions.py|CHANGELOG.rst|docs/contributing/doc_guide.rst

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
    name: noqa comments have an error code
    exclude: ^docs/plasmapy_sphinx/
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    name: codespell (add false positives to pyproject.toml)
    args: [--write-changes]
    additional_dependencies:
    - tomli

- repo: https://github.com/crate-ci/typos
  rev: v1.23.6
  hooks:
  - id: typos
    name: typos (add false positives to _typos.toml)

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
  - id: ruff
    name: ruff (see https://docs.astral.sh/ruff/rules)
    args: [--fix]
  - id: ruff-format
    name: autoformat source code with ruff-format

- repo: https://github.com/asottile/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    name: autoformat code blocks in docs
    # docstrings are formatted using the ruff-format hook
    exclude: docs/contributing/coding_guide.rst|.*\.py
    additional_dependencies:
    - black==24.4.2

- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v0.9.1
  hooks:
  - id: sphinx-lint

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.8.7
  hooks:
  - id: nbqa-check-ast
    name: validate Python notebooks
  - id: nbqa-ruff
    name: ruff for notebooks (see https://docs.astral.sh/ruff/rules)
    args: [--fix, '--select=A,ARG,B,BLE,C,C4,E,F,FLY,I,INT,ISC,PERF,PIE,PLC,PLE,PYI,Q003,RET,RSE,SIM,TID,TRY,UP,W', '--ignore=B007,B008,B015,B018,E402,E501,E741,PLC2401,PLC2403,SIM114']
