ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
    name: check for git merge conflicts
    exclude: .*\.rst
  - id: check-case-conflict
    name: check for filename case conflicts
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/sirosen/texthooks
  rev: 0.6.6
  hooks:
  - id: fix-smartquotes
  - id: fix-spaces
  - id: fix-ligatures
  - id: forbid-bidi-controls

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/crate-ci/typos
  rev: v1.23.6
  hooks:
  - id: typos
    name: detect typos (add false positives to _typos.toml)
