title = 'Pathways to Fusion'
baseURL = 'https://pathwaystofusion.github.io/'
languageCode = 'en-us'
Theme = "ananke"

sectionPagesMenu = 'main'

[menus]

# Menus are ordered from lowest weight to highest

[[menus.main]]
name = 'Overview'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Healthy to Innovative Framework'
pageRef = '/hti'
weight = 20

[[menus.main]]
name = 'Partners'
pageRef = '/partners'
weight = 30

[params]
    disabled_logo = false
    logo_text = "Pathways"
    logo = "img/logo.png"
