title = 'Pathways to Fusion'
baseURL = 'https://pathwaystofusion.github.io/'
languageCode = 'en-us'
Theme = "ananke"

sectionPagesMenu = 'main'

[menus]

# Menus are ordered from lowest weight to highest

[[menus.main]]
name = 'Introduction'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Resources'
pageRef = '/resources/'
weight = 20

[[menus.main]]
name = 'Partners'
pageRef = '/partners/'
weight = 30

[params]
disabled_logo = false
logo_text = "Pathways"
logo = "img/logo.png"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.extensions]
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.renderer]
      unsafe = true  # to allow html tags like <sup> to be used
